config/routes.rb
Rails.application.routes.draw do
  resources :data_streams

end

app/models/data_stream.rb
class DataStream < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_streams_controller.rb
class DataStreamsController < ApplicationController
  before_action :set_data_stream, only: [:show, :edit, :update, :destroy]

  # GET /data_streams
  # GET /data_streams.json
  def index
    @data_streams = DataStream.all
  end

  # GET /data_streams/1
  # GET /data_streams/1.json
  def show
  end

  # GET /data_streams/new
  def new
    @data_stream = DataStream.new
  end

  # GET /data_streams/1/edit
  def edit
  end

  # POST /data_streams
  # POST /data_streams.json
  def create
    @data_stream = DataStream.new(data_stream_params)

    respond_to do |format|
      if @data_stream.save
        format.html { redirect_to @data_stream, notice: 'Data stream was successfully created.' }
        format.json { render :show, status: :created, location: @data_stream }
      else
        format.html { render :new }
        format.json { render json: @data_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_streams/1
  # PATCH/PUT /data_streams/1.json
  def update
    respond_to do |format|
      if @data_stream.update(data_stream_params)
        format.html { redirect_to @data_stream, notice: 'Data stream was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_stream }
      else
        format.html { render :edit }
        format.json { render json: @data_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_streams/1
  # DELETE /data_streams/1.json
  def destroy
    @data_stream.destroy
    respond_to do |format|
      format.html { redirect_to data_streams_url, notice: 'Data stream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_stream
      @data_stream = DataStream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_stream_params
      params.require(:data_stream).permit(:name, :csdl, :active)
    end
  
    require 'datasift'
  
    def initialize
      @username = 'DATASIFT_USERNAME'
      @api_key = 'DATASIFT_API_KEY'
      @config = {:username => @username, :api_key => @api_key, :enable_ssl => true}
      @params = {:output_type =>   's3',
                                    'output_params.bucket' => 'YOUR_BUCKET_NAME',
                                    'output_params.directory' => 'ruby',
                                    'output_params.acl' => 'private',
                                    'output_params.auth.access_key' => 'ADD_YOUR_ACCESS_KEY',
                                    'output_params.auth.secret_key' => 'ADD_YOUR_SECRET_KEY',
                                    'output_params.delivery_frequency' => 0,
                                    'output_params.max_size' => 104857600,
                                    'output_params.file_prefix' => 'DataSift',
              }
      @pull_params = {:output_type =>   'pull',
                                        'output_params.max_size' => 52428800
                     }
      @datasift = DataSift::Client.new(@config)
  end
  
  attr_reader :datasift

  def create_push(hash, is_historics_id = false)
    create_params = @params.merge ({#hash or historics_id can be used but not both
      :name => 'My awesome push subscription',
      :initial_status => 'active', # or 'paused' or 'waiting_for_start'
      })
    if is_historics_id
      create_params.merge!({:historics_id => hash})
    else
      create_params.merge!({:hash => hash,
        #start and end are not valid for historics
        :start => Time.now.to_i,
        :end => Time.now.to_i + 320
        })
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_streams_helper.rb
module DataStreamsHelper
end

app/views/data_streams/_form.html.erb
<%= form_for(@data_stream) do |f| %>
  <% if @data_stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_stream.errors.count, "error") %> prohibited this data_stream from being saved:</h2>

      <ul>
      <% @data_stream.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :csdl %><br>
    <%= f.text_field :csdl %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_streams/edit.html.erb
<h1>Editing data_stream</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_stream %> |
<%= link_to 'Back', data_streams_path %>

app/views/data_streams/index.html.erb
<h1>Listing data_streams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Csdl</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_streams.each do |data_stream| %>
      <tr>
        <td><%= data_stream.name %></td>
        <td><%= data_stream.csdl %></td>
        <td><%= data_stream.active %></td>
        <td><%= link_to 'Show', data_stream %></td>
        <td><%= link_to 'Edit', edit_data_stream_path(data_stream) %></td>
        <td><%= link_to 'Destroy', data_stream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data stream', new_data_stream_path %>

app/views/data_streams/new.html.erb
<h1>New data_stream</h1>

<%= render 'form' %>

<%= link_to 'Back', data_streams_path %>

app/views/data_streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @data_stream.name %>
</p>

<p>
  <strong>Csdl:</strong>
  <%= @data_stream.csdl %>
</p>

<p>
  <strong>Active:</strong>
  <%= @data_stream.active %>
</p>

<%= link_to 'Edit', edit_data_stream_path(@data_stream) %> |
<%= link_to 'Back', data_streams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HairyOctoSansa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>